
export const LOAD_HEROES_SUCCESS = 'LOAD_HEROES_SUCCESS';
export const CREATE_HERO_SUCCESS = "CREATE_HERO_SUCCESS";
export const UPDATE_HERO_SUCCESS = "UPDATE_HERO_SUCCESS";
export const DELETE_HERO_SUCCESS = "DELETE_HERO_SUCCESS";
export const LOAD_MESSAGE_SUCCESS = "LOAD_MESSAGE_SUCCESS";
